g swp-public -
g swp-admin -
g swp-oauth -
g swp-pg -

u swp_backend - "Spotify Wallpaper backend" /nonexistent /usr/sbin/nologin
u swp_migrator - "Spotify Wallpaper migrator" /nonexistent /usr/sbin/nologin
u swp_backup - "Spotify Wallpaper backup" /nonexistent /usr/sbin/nologin
u swp_restore - "Spotify Wallpaper restore" /nonexistent /usr/sbin/nologin
u swp_maintenance - "Spotify Wallpaper maintenance" /nonexistent /usr/sbin/nologin
u oauth2-proxy - "Spotify Wallpaper OAuth2 Proxy" /nonexistent /usr/sbin/nologin

m postgres swp-pg
m swp_backend swp-pg
m swp_migrator swp-pg
m swp_backup swp-pg
m swp_restore swp-pg
m swp_maintenance swp-pg
m caddy swp-public
m caddy swp-oauth
m oauth2-proxy swp-admin
