# TYPE  DATABASE                            USER             METHOD
local   all                                postgres         peer
local   spotify_wallpaper                  swp_backend      peer
local   spotify_wallpaper_deletion_ledger  swp_backend      peer
local   spotify_wallpaper                  swp_migrator     peer
local   spotify_wallpaper_deletion_ledger  swp_migrator     peer
local   spotify_wallpaper                  swp_backup       peer
local   spotify_wallpaper_deletion_ledger  swp_backup       peer
local   all                                swp_restore      peer
local   spotify_wallpaper                  swp_maintenance  peer
local   spotify_wallpaper_deletion_ledger  swp_maintenance  peer
local   all                                all              reject
