d /run/spotify-wallpaper 0755 root root -
d /run/spotify-wallpaper/public 2770 swp_backend swp-public -
d /run/spotify-wallpaper/admin 2770 swp_backend swp-admin -
d /run/spotify-wallpaper/oauth 2770 oauth2-proxy swp-oauth -
d /var/backups/spotify-wallpaper 0700 root root -
