FROM node:22-bookworm-slim AS node
FROM caddy:2 AS caddy

FROM postgres:17.10-bookworm
COPY --from=node /usr/local/ /usr/local/
COPY --from=caddy /usr/bin/caddy /usr/bin/caddy
RUN ln -s /usr/local/bin/node /usr/bin/node \
    && apt-get update \
    && apt-get install --yes --no-install-recommends curl systemd \
    && rm -rf /var/lib/apt/lists/*
